### ISSUE TITLE
line replacement of paperless-ngx config file fails on content in paperless_ngx_conf_filename_format

### ISSUE THREAD

**Issue by borismw** [paperless-ngx/ansible#241]
Steps to reproduce:
- define a storage path template with placeholders, e.g. `'{% raw %}{{ created_year_short }}-{{ correspondent }}-{{ title }}{% endraw %}'` in variable `paperless_ngx_conf_filename_format`
- execute role

What happens:
The role execution fails because `created_year_short` variable does not exist.

---
Hi 👋🏾,

again thanks this ansible role. It made settings up paperless-ngx easy, event though documentation of the bare-metal route is a bit scarce. I ran into problems when defining a `paperless_ngx_conf_filename_format` as mentioned above. It seems that even when wrapped between `{% raw %}...{% endraw %}` the `ansible.builtin.lineinfile` task interprets the paperless-ngx specific placeholde syntax as Jinja variable expressions and tries to expand them. This of course leads to an error because the paperless-ngx specific text templates are not known to ansible.

I found out that by escaping the loop entry for `paperless_ngx_conf_filename_format` in the `Write the paperless-ngx config file` task in `tasks/paperless_ngx/configuration.yml` like so
```
    - pngx_var: PAPERLESS_FILENAME_FORMAT
      role_var: "{{ '{{' }} paperless_ngx_conf_filename_format {{ '}}' }}"
```
fixes the problem. But same as the issue I filed a few days ago I do not know if this solution fits in. However I will open up a PR soon. EDIT: see PR #242

**Comment by stevenengland** [comment]
fixed via #242 that was slightly improved in #250

**Comment by Boring-Mind** [comment]
I believe, this bug was not fixed properly. I have the latest Paperless-ngx installed. And I don't provide any value into this setting from Ansible role. And Paperless-ngx produces warnings, since the resulting value in /etc/paperless.conf is literally this: `{{ paperless_ngx_conf_filename_format }}`
